// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winterplein.Infrastructure;

#nullable disable

namespace Winterplein.Infrastructure.Migrations
{
    [DbContext(typeof(WinterpleinDbContext))]
    [Migration("20260617192732_AddPlannedMatches")]
    partial class AddPlannedMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeasonPlayers", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("PlayersId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonPlayers");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Team1Id")
                        .HasColumnType("int");

                    b.Property<int>("Team2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.PlannedMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlannedMatches");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.Property<int>("Weekday")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SeasonPlayers", b =>
                {
                    b.HasOne("Winterplein.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Winterplein.Domain.Entities.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Match", b =>
                {
                    b.HasOne("Winterplein.Domain.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Winterplein.Domain.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.PlannedMatch", b =>
                {
                    b.OwnsOne("Winterplein.Domain.Entities.PlannedTeam", "Team1", b1 =>
                        {
                            b1.Property<int>("PlannedMatchId")
                                .HasColumnType("int");

                            b1.HasKey("PlannedMatchId");

                            b1.ToTable("PlannedMatches");

                            b1.WithOwner()
                                .HasForeignKey("PlannedMatchId");

                            b1.OwnsOne("Winterplein.Domain.Entities.PlannedPlayer", "Player1", b2 =>
                                {
                                    b2.Property<int>("PlannedTeamPlannedMatchId")
                                        .HasColumnType("int");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player1FirstName");

                                    b2.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player1Gender");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player1LastName");

                                    b2.Property<int>("PlayerId")
                                        .HasColumnType("int")
                                        .HasColumnName("Team1Player1PlayerId");

                                    b2.HasKey("PlannedTeamPlannedMatchId");

                                    b2.ToTable("PlannedMatches");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedTeamPlannedMatchId");
                                });

                            b1.OwnsOne("Winterplein.Domain.Entities.PlannedPlayer", "Player2", b2 =>
                                {
                                    b2.Property<int>("PlannedTeamPlannedMatchId")
                                        .HasColumnType("int");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player2FirstName");

                                    b2.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player2Gender");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team1Player2LastName");

                                    b2.Property<int>("PlayerId")
                                        .HasColumnType("int")
                                        .HasColumnName("Team1Player2PlayerId");

                                    b2.HasKey("PlannedTeamPlannedMatchId");

                                    b2.ToTable("PlannedMatches");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedTeamPlannedMatchId");
                                });

                            b1.Navigation("Player1")
                                .IsRequired();

                            b1.Navigation("Player2")
                                .IsRequired();
                        });

                    b.OwnsOne("Winterplein.Domain.Entities.PlannedTeam", "Team2", b1 =>
                        {
                            b1.Property<int>("PlannedMatchId")
                                .HasColumnType("int");

                            b1.HasKey("PlannedMatchId");

                            b1.ToTable("PlannedMatches");

                            b1.WithOwner()
                                .HasForeignKey("PlannedMatchId");

                            b1.OwnsOne("Winterplein.Domain.Entities.PlannedPlayer", "Player1", b2 =>
                                {
                                    b2.Property<int>("PlannedTeamPlannedMatchId")
                                        .HasColumnType("int");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player1FirstName");

                                    b2.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player1Gender");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player1LastName");

                                    b2.Property<int>("PlayerId")
                                        .HasColumnType("int")
                                        .HasColumnName("Team2Player1PlayerId");

                                    b2.HasKey("PlannedTeamPlannedMatchId");

                                    b2.ToTable("PlannedMatches");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedTeamPlannedMatchId");
                                });

                            b1.OwnsOne("Winterplein.Domain.Entities.PlannedPlayer", "Player2", b2 =>
                                {
                                    b2.Property<int>("PlannedTeamPlannedMatchId")
                                        .HasColumnType("int");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player2FirstName");

                                    b2.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player2Gender");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Team2Player2LastName");

                                    b2.Property<int>("PlayerId")
                                        .HasColumnType("int")
                                        .HasColumnName("Team2Player2PlayerId");

                                    b2.HasKey("PlannedTeamPlannedMatchId");

                                    b2.ToTable("PlannedMatches");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedTeamPlannedMatchId");
                                });

                            b1.Navigation("Player1")
                                .IsRequired();

                            b1.Navigation("Player2")
                                .IsRequired();
                        });

                    b.Navigation("Team1")
                        .IsRequired();

                    b.Navigation("Team2")
                        .IsRequired();
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("Winterplein.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastName");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Winterplein.Domain.Entities.Team", b =>
                {
                    b.HasOne("Winterplein.Domain.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Winterplein.Domain.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });
#pragma warning restore 612, 618
        }
    }
}
